### PR TITLE
health and colour of livid in chat

### PR DESCRIPTION
**Pull request by Dolphin0xyz**
When you fight livid the health and colour (the name tag) are put at the bottom of the chat.

### CODE REVIEW

**Comment by Dolphin0xyz** [comment]
this sometimes focuses on the wrong livid/changes half way through the fight but that is the whole livid detector, not just this addition.

**Comment by Antonio32A** [comment]
What's the point of setting a new line id, and this executed every tick btw?

**Comment by Dolphin0xyz** [comment]
> What's the point of setting a new line id, and this executed every tick btw?

The ChatLineID means the chat won't be spammed because the message replaces the previous one.

 It's executed every tick because I put it in the same block of code that finds the correct livid.

**Comment by Antonio32A** [comment]
Are you sure that CT message line ids aren't the same as MC message line ids?

**Comment by Dolphin0xyz** [comment]
don't know

**Comment by Antonio32A** [comment]
Are you able to test it?

**Comment by Dolphin0xyz** [comment]
how would I do that?

**Comment by Antonio32A** [comment]
Just set it to a lower number and let the game run with gchat for a few hours, then do a run.

**Comment by Dolphin0xyz** [comment]
how would I know if it conflicted with an MC message line id?

**Comment by Antonio32A** [comment]
It should just not appear, or appear somewhere else.

**Comment by Dolphin0xyz** [comment]
i had the id set to 5 and it worked fine

**Pull request merged**
